name: zumolla_server
version: 0.1.0
author: www.eldardo.org
description: A server layer on top of Rikulo Stream which lets user implement specialized controllers like servlets, JSON, JSON CRUD by extending the corresponding base class.
homepage: https://github.com/el-dardo/zumolla_server
dependencies:
  intl: any
  json_object: any
  stream: any
dev_dependencies:
  unittest: any

#dependencies:
#  unittest: any