//Auto-generated by RSP Compiler
//Source: articles_view.rsp.html
library articles_view_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';
import '../json/entities.dart';

/** Template, articles_view, for rendering the view. */
Future articles_view(HttpConnect connect, {List<Article> articles}) { //#1
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = ContentType.parse("""text/html; charset=utf-8""");

  response.write("""

<!DOCTYPE html>
<html>
  <head>
    <title>
      Artículos 
    </title>
    <link href="/styles.css" rel="stylesheet" type="text/css" />
  </head>
  <body class="articlesView">
    
    <h1>Artículos</h1>
        
"""); //#1

  for (var article in articles) { //for#14

    response.write("""

      <div class="title">"""); //#14

    response.write(Rsp.nnx(article.title)); //#15


    response.write("""
</div>
      <div class="author">"""); //#15

    response.write(Rsp.nnx(article.author.fullName)); //#16


    response.write("""
</div>
      <div class="intro">"""); //#16

    response.write(Rsp.nnx(article.intro)); //#17


    response.write("""
</div>
      <div class="content">"""); //#17

    response.write(Rsp.nnx(article.content)); //#18


    response.write("""
</div>
      <hr/>
"""); //#18
  } //for

  response.write("""

     
    <!--
    <script type="application/dart" src="/client/authors_view.dart"></script>
    <script src="/packages/browser/dart.js"></script>
    -->

  </body>
</html>
"""); //#20

  return Rsp.nnf();
}
