//Auto-generated by RSP Compiler
//Source: example/web/webapp/view/article_view.rsp.html
part of views;

/** Template, article_view, for rendering the view. */
Future article_view(HttpConnect connect, {String articleId,Article article}) { //#1
  var _t0_, _cs_ = new List<HttpConnect>(),
  request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = ContentType.parse("""text/html; charset=utf-8""");

  response.write("""

<!DOCTYPE html>
<html>
  <head>
    <title>
      """); //#1

  response.write(RSP.nns(article.title)); //#6


  response.write("""

    </title>
    <link href="/styles.css" rel="stylesheet" type="text/css" />
  </head>
  <body class="articleView">
    
    <h1>"""); //#6

  response.write(RSP.nns(article.title)); //#12


  response.write("""
</h1>
    
    <div class="intro">"""); //#12

  response.write(RSP.nns(article.intro)); //#14


  response.write("""
</div>
    <div class="content">"""); //#14

  response.write(RSP.nns(article.content)); //#15


  response.write("""
</div>
    <div class="author">
      <div class="tag">Información del autor</div>
      <div class="name">"""); //#15

  response.write(RSP.nns(article.author.name)); //#18


  response.write("""
</div>
      <div class="surname">"""); //#18

  response.write(RSP.nns(article.author.surname)); //#19


  response.write("""
</div>
      <div class="email">"""); //#19

  response.write(RSP.nns(article.author.email)); //#20


  response.write("""
</div>
      <div class="moreInfoLink">"""); //#20

  response.write(RSP.nns(article.author.moreInfoLink)); //#21


  response.write("""
</div>
    </div>

    <!--
    <script type="application/dart" src="/client/article_view.dart"></script>
    <script src="/packages/browser/dart.js"></script>
    -->

  </body>
</html>
"""); //#21

  return RSP.nnf();
}
