//Auto-generated by RSP Compiler
//Source: author_view.rsp.html
library author_view_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';
import '../json/entities.dart';

/** Template, author_view, for rendering the view. */
Future author_view(HttpConnect connect, {Author author}) { //#1
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = ContentType.parse("""text/html; charset=utf-8""");

  response.write("""

<!DOCTYPE html>
<html>
  <head>
    <title>
      """); //#1

  response.write(Rsp.nnx(author.name)); //#6


  response.write(""" """); //#6

  response.write(Rsp.nnx(author.surname)); //#6


  response.write("""
 
    </title>
    <link href="/styles.css" rel="stylesheet" type="text/css" />
  </head>
  <body class="authorView">
    
    <h1>"""); //#6

  response.write(Rsp.nnx(author.name)); //#12


  response.write(""" """); //#12

  response.write(Rsp.nnx(author.surname)); //#12


  response.write("""
</h1>
    
    <div class="email">"""); //#12

  response.write(Rsp.nnx(author.email)); //#14


  response.write("""
</div>
    <div class="moreInfoLink">"""); //#14

  response.write(Rsp.nnx(author.moreInfoLink)); //#15


  response.write("""
</div>

    <!--
    <script type="application/dart" src="/client/author_view.dart"></script>
    <script src="/packages/browser/dart.js"></script>
    -->

  </body>
</html>
"""); //#15

  return Rsp.nnf();
}
