//Auto-generated by RSP Compiler
//Source: example/web/webapp/view/authors_view.rsp.html
part of views;

/** Template, authors_view, for rendering the view. */
Future authors_view(HttpConnect connect, {List<Author> authors}) { //#1
  var _t0_, _cs_ = new List<HttpConnect>(),
  request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = ContentType.parse("""text/html; charset=utf-8""");

  response.write("""

<!DOCTYPE html>
<html>
  <head>
    <title>
      Autores 
    </title>
    <link href="/styles.css" rel="stylesheet" type="text/css" />
  </head>
  <body class="authorsView">
    
    <h1>Autores</h1>
    
    <table>
      <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>E-mail</th>
        <th>More info</th>
      </tr>
"""); //#1

  for (var author in authors) { //for#21

    response.write("""

        <tr>
          <td class="name">"""); //#21

    response.write(RSP.nns(author.name)); //#23


    response.write("""
</td>
          <td class="surname">"""); //#23

    response.write(RSP.nns(author.surname)); //#24


    response.write("""
</td>
          <td class="email">"""); //#24

    response.write(RSP.nns(author.email)); //#25


    response.write("""
</td>
          <td class="moreInfoLink">"""); //#25

    response.write(RSP.nns(author.moreInfoLink)); //#26


    response.write("""
</td>
        </tr>
"""); //#26
  } //for

  response.write("""

    </table>
     
    <!--
    <script type="application/dart" src="/client/authors_view.dart"></script>
    <script src="/packages/browser/dart.js"></script>
    -->

  </body>
</html>
"""); //#28

  return RSP.nnf();
}
