//Auto-generated by RSP Compiler
//Source: example/web/webapp/view/author_view.rsp.html
part of views;

/** Template, author_view, for rendering the view. */
Future author_view(HttpConnect connect, {Author author}) { //#1
  var _t0_, _cs_ = new List<HttpConnect>(),
  request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = ContentType.parse("""text/html; charset=utf-8""");

  response.write("""

<!DOCTYPE html>
<html>
  <head>
    <title>
      """); //#1

  response.write(RSP.nns(author.name)); //#6


  response.write(""" """); //#6

  response.write(RSP.nns(author.surname)); //#6


  response.write("""
 
    </title>
    <link href="/styles.css" rel="stylesheet" type="text/css" />
  </head>
  <body class="authorView">
    
    <h1>"""); //#6

  response.write(RSP.nns(author.name)); //#12


  response.write(""" """); //#12

  response.write(RSP.nns(author.surname)); //#12


  response.write("""
</h1>
    
    <div class="email">"""); //#12

  response.write(RSP.nns(author.email)); //#14


  response.write("""
</div>
    <div class="moreInfoLink">"""); //#14

  response.write(RSP.nns(author.moreInfoLink)); //#15


  response.write("""
</div>

    <!--
    <script type="application/dart" src="/client/author_view.dart"></script>
    <script src="/packages/browser/dart.js"></script>
    -->

  </body>
</html>
"""); //#15

  return RSP.nnf();
}
